version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
      target: init-build
    depends_on:
      - db
    ports:
      - "5555:5000"
    networks:
      server_net:
        ipv4_address: 11.0.0.2


  db:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - "3443:3443"
    networks:
      server_net:
        ipv4_address: 11.0.0.1

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
      target: init-build 
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ./app/static
        target: /kagajpatra/app/static
      - type: bind
        source: ./app/uploads
        target: /kagajpatra/app/uploads
    ports:
      - "8989:80"
    depends_on:
      - web
    networks:
      server_net:
        ipv4_address: 11.0.0.3

networks:
  server_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "11.0.0.0/24"
