version: "3.8"
services:
  web:
    image: kagajpatra_web:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - server_overlay
 
  db:
    image: mysql:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - server_overlay
  
  nginx:
    image: nginx:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app/static:/kagajpatra/app/static
      - ./app/uploads:/kagajpatra/app/uploads
    ports:
      - "8110:80"
    depends_on:
      - web
    networks:
      - server_overlay

networks:
  server_overlay:
    driver: overlay
    driver_opts:
      subnet: 10.0.1.0/24
