version: 3.8
  services:
    web:
      image: harbor.registry.local/kagajpatra/web:$BUILD_NUMBER
      ports:
        - "5000:5000"
      networks:
        - server_net
    db:
      image: harbor.registry.local/kagajpatra/db:$BUILD_NUMBER
      env_file:
        - .env
      ports:
        - "3306:3306"
      networks:
        - server_net
    nginx:
      image: harbor.registry.local/kagajpatra/nginx:$BUILD_NUMBER
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./app/static:/kagajpatra/app/static
        - ./app/uploads:/kagajpatra/app/uploads
      ports:
        - "8200:80"
      networks:
        - server_net

  networks:
    server_net:
      ipam:
        subnet:
          - "11.0.0.0/24"
        
        
