version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
      target: init-build
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      server_net:
        ipv4_address: 10.0.1.3


  db:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      server_net:
        ipv4_address: 10.0.1.2

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
      target: init-build 
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ./app/static
        target: /kagajpatra/app/static
      - type: bind
        source: ./app/uploads
        target: /kagajpatra/app/uploads
    ports:
      - "8111:80"
    depends_on:
      - web
    networks:
      server_net:
        ipv4_address: 10.0.1.3

networks:
  server_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.0.1.0/24"
