#Dockerfile for python web app
FROM python:3.9-slim as init-build
WORKDIR /kagajpatra
COPY requirements.txt .
RUN pip install --upgrade pip \
    && pip install -r requirements.txt
COPY . .
CMD ["python", "app.py"]
