version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
  
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'kagajpatra'
      MYSQL_USER: 'rabin'
      MYSQL_PASSWORD: 'Rabin@123'
      MYSQL_ROOT_PASSWORD: 'Rabin@1234'
    ports:
      - "3306:3306"
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app/static:/app/app/static
      - ./app/uploads:/app/app/uploads
    ports:
      - "8110:80"
    depends_on:
      - web
