FROM nginx:latest as init-build

WORKDIR /kagajpatra
#Copy the Nginx configuration file into the container
COPY nginx/nginx.conf /etc/nginx/nginx.conf

#Remove the default Nginx Configuration file
RUN rm /etc/nginx/conf.d/default.conf \
    && mkdir app || true

#Expose port 80 to the outside world
EXPOSE 80

#Run Nginx when the container launches
CMD ["nginx", "-g", "daemon off;"]
