version: '3.8'
services:
  web:
    image: harbor.registry.local/kagajpatra/web:$BUILD_NUMBER
    ports:
      - "5000:5000"
    networks:
      - server_net
    volumes:
      - ./app:/app # Mount the app directory into the container for code changes
  db:
    image: harbor.registry.local/kagajpatra/mysql:$BUILD_NUMBER
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - server_net
  nginx:
    image: harbor.registry.local/kagajpatra/nginx:$BUILD_NUMBER
    volumes:
      - ./app:/kagajpatra/app
    ports:
      - "8081:80"
    networks:
      - server_net

networks:
  server_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "11.0.1.0/24"
        
